name: oftable_flutter
description: 오떼 플러터

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 스플래시 페이지 플러그인
  flutter_native_splash: ^1.0.3
  # sns 가입 버튼
  sign_button: ^1.0.2
  # 종료 2번 딱딱
  double_back_to_close_app: ^2.0.1
  # http
  http: ^0.13.0
  #자동로그인데이터 저장소 플러그인
  flutter_secure_storage: ^4.1.0
  # 우편번호 찾기
  kopo: "^0.1.3"
  #구글 소셜로그인
  google_sign_in: ^5.0.1
  #getX
  get: ^4.1.1
  #리스트타일 슬라이드
  flutter_slidable: ^0.5.7
  #비디오플레이어
  video_player: ^2.1.1
  #스피너
  flutter_spinkit: ^5.0.0
  youtube_player_iframe: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/lifestyle/
     - assets/keyword/
     - assets/favor/
     - assets/alergy/
     - assets/background/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Supersize_Black
     fonts:
       - asset: fonts/Supersize_Black.ttf
   - family: national_park_outline
     fonts:
       - asset: fonts/national_park_outline.otf
   - family: NanumGothic
     fonts:
       - asset: fonts/NanumFont/NanumGothic.ttf
       - asset: fonts/NanumFont/NanumGothicExtraBold.ttf
         weight: 800
   - family: Poppins
     fonts:
       - asset: fonts/Poppins/Poppins-Bold.ttf
   - family: Campton
     fonts:
       - asset: fonts/Campton/Campton-Bold.ttf
       - asset: fonts/Campton/Campton-Light.otf
         weight: 100
   - family: SourceHanSansKR
     fonts:
       - asset: fonts/SourceHanSansKR_Normal.otf
       - asset: fonts/SourceHanSansKR_Bold.otf
         weight: 800
       - asset: fonts/SourceHanSansKR_Heavy.otf
         weight: 900
       - asset: fonts/SourceHanSansKR_Light.otf
         weight: 200
       - asset: fonts/SourceHanSansKR_ExtraLight.otf
         weight: 100
       - asset: fonts/SourceHanSansKR_Medium.otf
         weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
